Class {
	#name : #BlueprintModel,
	#superclass : #ProjectModel,
	#category : #ProjectsAnalyzer
}

{ #category : #accessing }
BlueprintModel >> model [ 
	^ model
]

{ #category : #accessing }
BlueprintModel >> nAbstractMethods [ 
	^ nAbstractMethods 
]

{ #category : #accessing }
BlueprintModel >> nClasses [ 
	^ nClasses 
]

{ #category : #accessing }
BlueprintModel >> nComplexMethods [ 
	^ nComplexMethods 
]

{ #category : #accessing }
BlueprintModel >> nDeadAttributes [ 
	^ nDeadAttributes 
]

{ #category : #accessing }
BlueprintModel >> nDeadMethods [ 
	^ nDeadMethods 
]

{ #category : #accessing }
BlueprintModel >> nExtendingMethods [ 
	^ nExtendingMethods 
]

{ #category : #accessing }
BlueprintModel >> nMegamorphicMethods [ 
	^ nMegamorphicMethods 
]

{ #category : #accessing }
BlueprintModel >> nMethods [ 	
	^ nMethods
]

{ #category : #accessing }
BlueprintModel >> nMonomorphicMethods [ 
	^ nMonomorphicMethods
]

{ #category : #accessing }
BlueprintModel >> nOverridenMethods [ 
	^ nOverridenMethods 
]

{ #category : #accessing }
BlueprintModel >> nOverridingMethods [
	^ nOverridingMethods 
]

{ #category : #accessing }
BlueprintModel >> nPackages [ 
	^ nPackages 
]

{ #category : #accessing }
BlueprintModel >> nPolymorphicMethods [ 
	^ nPolymorphicMethods
]

{ #category : #accessing }
BlueprintModel >> nTestedMethods [ 
	^ nTestedMethods 
]

{ #category : #accessing }
BlueprintModel >> name [ 
	^ name
]
