name: Run tests

on: [ push, workflow_dispatch ]
 
jobs:
  run:
    uses: moosetechnology/.github/.github/workflows/run-tests.yml@main
    with:
     run-coverage: true
     pharo-versions: ${{ vars.MOOSE_PHARO_VERSIONS['Moose-latest'] }}
